#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Oct 04, 2018 03:38:18 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top37.tNo38.pg0 
    set site_4_0 $site_4_0
    set site_4_1 .top37.tNo38.pg1 
    set site_4_0 $site_4_1
    set site_5_0 $site_4_0.tLa37
    set site_5_0 $site_4_0.tLa38
    set site_5_0 $site_4_0.tLa39
    set site_5_0 $site_4_0.tLa40
    set site_4_2 .top37.tNo38.pg6 
    set site_4_0 $site_4_2
    set site_5_0 $site_4_0.tLa37
    set site_5_0 $site_4_0.cpd42
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 603x581+292+132
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1032
    wm minsize $top 126 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "GUI" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo38 \
        -width 569 -height 506 -takefocus {} 
    vTcl:DefineAlias "$top.tNo38" "TNotebook1" vTcl:WidgetProc "GUI" 1
    frame .top37.tNo38.pg0 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg0 \
        -padding 0 -sticky nsew -state normal -text Seriale -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo38.pg0
    entry $site_4_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable portaSeriale 
    vTcl:DefineAlias "$site_4_0.ent40" "Entry1" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.apriSeriale \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Usa questa} 
    vTcl:DefineAlias "$site_4_0.but41" "Button1" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.apriFTDI \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Usa FTDI} 
    vTcl:DefineAlias "$site_4_0.but37" "Button47" vTcl:WidgetProc "GUI" 1
    place $site_4_0.ent40 \
        -in $site_4_0 -x 130 -y 110 -width 390 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but41 \
        -in $site_4_0 -x 30 -y 110 -width 80 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but37 \
        -in $site_4_0 -x 30 -y 165 -width 80 -height 25 -anchor nw \
        -bordermode ignore 
    frame .top37.tNo38.pg1 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg1 \
        -padding 0 -sticky nsew -state normal -text Varie -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo38.pg1
    button $site_4_1.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.Eco -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Eco 
    vTcl:DefineAlias "$site_4_1.but37" "Button2" vTcl:WidgetProc "GUI" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_1.tLa37 \
        -text Prova -width 230 -height 115 
    vTcl:DefineAlias "$site_4_1.tLa37" "TLabelframe1" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.tLa37
    label $site_5_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Invia 
    vTcl:DefineAlias "$site_5_0.lab39" "Label2" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable numEco 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry2" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Eco 
    vTcl:DefineAlias "$site_5_0.but41" "Button3" vTcl:WidgetProc "GUI" 1
    bind $site_5_0.but41 <ButtonRelease-1> {
        self.ecoProva
    }
    ttk::progressbar $site_5_0.tPr43 \
        -mode indeterminate 
    vTcl:DefineAlias "$site_5_0.tPr43" "TProgressbar1" vTcl:WidgetProc "GUI" 1
    place $site_5_0.lab39 \
        -in $site_5_0 -x 20 -y 25 -width 39 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 75 -y 25 -width 69 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but41 \
        -in $site_5_0 -x 160 -y 25 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tPr43 \
        -in $site_5_0 -x 30 -y 65 -width 180 -height 22 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_1.tLa38 \
        -text Versione -width 257 -height 73 
    vTcl:DefineAlias "$site_4_1.tLa38" "TLabelframe2" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.tLa38
    button $site_5_0.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.revisione \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Revisione 
    vTcl:DefineAlias "$site_5_0.but39" "Button4" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black -state readonly \
        -textvariable revisione 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry3" vTcl:WidgetProc "GUI" 1
    place $site_5_0.but39 \
        -in $site_5_0 -x 28 -y 27 -width 70 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 120 -y 23 -width 100 -height 25 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_1.tLa39 \
        -text Led -width 178 -height 110 
    vTcl:DefineAlias "$site_4_1.tLa39" "TLabelframe8" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.tLa39
    checkbutton $site_5_0.che40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Rosso -variable rosso 
    vTcl:DefineAlias "$site_5_0.che40" "Checkbutton1" vTcl:WidgetProc "GUI" 1
    checkbutton $site_5_0.che41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Verde -variable verde 
    vTcl:DefineAlias "$site_5_0.che41" "Checkbutton2" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.led -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Scrivi 
    vTcl:DefineAlias "$site_5_0.but43" "Button14" vTcl:WidgetProc "GUI" 1
    place $site_5_0.che40 \
        -in $site_5_0 -x 22 -y 28 -anchor nw -bordermode ignore 
    place $site_5_0.che41 \
        -in $site_5_0 -x 23 -y 61 -anchor nw -bordermode ignore 
    place $site_5_0.but43 \
        -in $site_5_0 -x 98 -y 33 -width 47 -height 50 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_1.tLa40 \
        -text Cicalino -width 270 -height 77 
    vTcl:DefineAlias "$site_4_1.tLa40" "TLabelframe10" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.tLa40
    label $site_5_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Frequenza 
    vTcl:DefineAlias "$site_5_0.lab41" "Label18" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent42 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable cicalino 
    vTcl:DefineAlias "$site_5_0.ent42" "Entry22" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Hz 
    vTcl:DefineAlias "$site_5_0.lab43" "Label19" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.cicalino \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Scrivi 
    vTcl:DefineAlias "$site_5_0.but44" "Button19" vTcl:WidgetProc "GUI" 1
    place $site_5_0.lab41 \
        -in $site_5_0 -x 18 -y 31 -anchor nw -bordermode ignore 
    place $site_5_0.ent42 \
        -in $site_5_0 -x 93 -y 27 -width 60 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab43 \
        -in $site_5_0 -x 167 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.but44 \
        -in $site_5_0 -x 200 -y 30 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_1.but37 \
        -in $site_4_1 -x 30 -y 25 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa37 \
        -in $site_4_1 -x 100 -y 10 -width 230 -height 115 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa38 \
        -in $site_4_1 -x 10 -y 130 -width 257 -height 73 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa39 \
        -in $site_4_1 -x 33 -y 331 -width 178 -height 110 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa40 \
        -in $site_4_1 -x 14 -y 227 -width 270 -height 77 -anchor nw \
        -bordermode ignore 
    frame .top37.tNo38.pg6 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg6 \
        -padding 0 -sticky nsew -state normal -text Parametri -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo38.pg6
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_2.tLa37 \
        -text Matricola -width 418 -height 125 
    vTcl:DefineAlias "$site_4_2.tLa37" "TLabelframe11" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_2.tLa37
    button $site_5_0.but38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.matLeggi \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Leggi 
    vTcl:DefineAlias "$site_5_0.but38" "Button33" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.matScrivi \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Scrivi 
    vTcl:DefineAlias "$site_5_0.but39" "Button34" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable matricola 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry31" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.matCrea \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Crea 
    vTcl:DefineAlias "$site_5_0.but37" "Button37" vTcl:WidgetProc "GUI" 1
    place $site_5_0.but38 \
        -in $site_5_0 -x 25 -y 38 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but39 \
        -in $site_5_0 -x 333 -y 39 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 92 -y 40 -width 224 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but37 \
        -in $site_5_0 -x 174 -y 79 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_2.cpd42 \
        -text Scheda -width 418 -height 132 
    vTcl:DefineAlias "$site_4_2.cpd42" "TLabelframe12" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_2.cpd42
    button $site_5_0.but38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.schLeggi \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Leggi 
    vTcl:DefineAlias "$site_5_0.but38" "Button35" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.schScrivi \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Scrivi 
    vTcl:DefineAlias "$site_5_0.but39" "Button36" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable scheda 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry32" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.schCrea \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Crea 
    vTcl:DefineAlias "$site_5_0.but40" "Button38" vTcl:WidgetProc "GUI" 1
    place $site_5_0.but38 \
        -in $site_5_0 -x 25 -y 38 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but39 \
        -in $site_5_0 -x 333 -y 39 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 92 -y 40 -width 224 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but40 \
        -in $site_5_0 -x 179 -y 85 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tLa37 \
        -in $site_4_2 -x 23 -y 20 -width 418 -height 125 -anchor nw \
        -bordermode ignore 
    place $site_4_2.cpd42 \
        -in $site_4_2 -x 24 -y 162 -width 418 -height 132 -anchor nw \
        -bordermode inside 
    label $top.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -textvariable Messaggio 
    vTcl:DefineAlias "$top.lab39" "Label1" vTcl:WidgetProc "GUI" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo38 \
        -in $top -x 15 -y 45 -width 569 -height 506 -anchor nw \
        -bordermode ignore 
    place $top.lab39 \
        -in $top -x 20 -y 10 -width 559 -height 21 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

